import { Inter } from 'next/font/google'
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";
import "../libs/fontawsome";
import Navbar from './Components/Navbar/Navbar';
import { ThemeContextProvider } from '@/Context/ThemeContext';
import ThemeProviders from '@/Providers/ThemeProviders';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <ThemeProviders>
            <div className="container">
              <div className="wrapper">
                <Navbar />
                <div>{children}</div>
                {/* <Footer /> */}
              </div>
            </div>
          </ThemeProviders>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
